# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
#
# SPDX-License-Identifier: GPL-3.0-only

name: 'SQAaaS source code assessment'
description: 'Trigger the source code assessment in SQAaaS'
author: 'Pablo Orviz <orviz@ifca.unican.es>'
branding:
  icon: "award"
  color: "orange"
inputs:
  repo:
    description: URL of the repository to assess
    required: true
  branch:
    description: Branch of the repository
    required: false
outputs:
  report:
    description: 'JSON payload containing the full QA report'
  badge_svg:
    description: 'Badge SVG file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
