name: 'SQAaaS source code assessment'
description: 'Trigger the source code assessment in SQAaaS'
author: 'Pablo Orviz <orviz@ifca.unican.es>'
inputs:
  repo:
    description: URL of the repository to assess
    required: true
  branch:
    description: Branch of the repository
    required: false
outputs:
  report:
    description: 'JSON payload containing the full QA report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
