# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only

name: 'SQAaaS source code assessment'
description: 'Trigger the source code assessment in SQAaaS'
author: 'Pablo Orviz <orviz@ifca.unican.es>'
branding:
  icon: "award"
  color: "orange"
inputs:
  repo:
    description: URL of the repository to assess (defaults to current repo)
    required: false
  branch:
    description: Branch of the repository (defaults to branch that triggered the build)
    required: false
  qc_uni_steps:
    description: space-separated list of steps for unit testing (QC.Uni) quality criterion (composed with sqaaas-step-action)
    required: false
outputs:
  report:
    description: 'JSON payload containing the full QA report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
    - ${{ inputs.qc_uni_steps }}
