# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
#
# SPDX-License-Identifier: GPL-3.0-only

on: [push]

jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    name: Job that triggers SQAaaS platform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SQAaaS action step
        uses: eosc-synergy/sqaaas-assessment-action@release/2.0.0
      - name: Clean image cache on README.md
        uses: wow-actions/purge-readme@v1